openapi: 3.0.3
info:
  title: API Specification
  version: 1.0.0
  description: A sample API specification
  contact: 
    name: Example API Support Team
    url: https://example.com/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
tags:
  - name: resources
    description: Operations related to resources
security: 
  -  BearerAuth: []    
paths:
  /resources:
    get:
      summary: Get resources
      description: Get a list of resources
      operationId: getResources
      tags: 
        -  resources
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a resource
      description: Create a new resource
      operationId: createResource
      tags: 
        -  resources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceInput'
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '400':
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Resource:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    ResourceInput:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    Error:
      type: object
      properties:
        title:
          type: string
        httpStatus:
          type: integer
        traceId:
          type: string
          format: uuid
        requestId:
          type: string
          format: uuid
        context:
          type: array
          items: 
            type: object
            properties:
              code:
                type: string
              message:
                type: string
              location:
                type: string
                enum: [HEADER, QUERY, PATH, BODY]
              field:
                type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer